[workspace]
members = [
    "crates/wreath-core",
    "crates/wreath-ui",
    "crates/wreath-win-ui",
    "crates/wreath-windows",
    "crates/wreathctl",
    "crates/wreathd",
]
resolver = "3"

[workspace.package]
version = "1.5.2"
edition = "2024"
license = "MIT"
repository = "https://github.com/mika2go/wreath"
rust-version = "1.85"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
gtk = { package = "gtk4", version = "0.11", features = ["v4_14"] }
gdk-pixbuf = "0.22"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = true
