pub mod audio;
pub mod clips;
pub mod config;
pub mod diagnostics;
pub mod display;
#[cfg(target_os = "linux")]
pub mod engine;
pub mod favorites;
#[cfg(target_os = "linux")]
pub mod hyprland;
pub mod ipc;
pub mod paths;
pub mod replay;
pub mod replay_buffer;
#[cfg(target_os = "linux")]
pub mod shortcuts;
pub mod trim;
#[cfg(target_os = "linux")]
pub mod trim_ffmpeg;
